// This file is auto-generated by Mingull's Minager CLI
// Do not edit manually
import { createLibraryRegistry } from "@mingull/registry";

export const registry = createLibraryRegistry({
	AngularIcon: () => import("./icons/angular-icon.tsx").then((mod) => mod.AngularIcon),
	AppleIcon: () => import("./icons/apple-icon.tsx").then((mod) => mod.AppleIcon),
	AriaIcon: () => import("./icons/aria-icon.tsx").then((mod) => mod.AriaIcon),
	DiscordIcon: () => import("./icons/discord-icon.tsx").then((mod) => mod.DiscordIcon),
	GitHubIcon: () => import("./icons/github-icon.tsx").then((mod) => mod.GitHubIcon),
	GoogleIcon: () => import("./icons/google-icon.tsx").then((mod) => mod.GoogleIcon),
	MySQLIcon: () => import("./icons/mysql-icon.tsx").then((mod) => mod.MySQLIcon),
	NextJsIcon: () => import("./icons/nextjs-icon.tsx").then((mod) => mod.NextJsIcon),
	NodeJsIcon: () => import("./icons/nodejs-icon.tsx").then((mod) => mod.NodeJsIcon),
	NPMIcon: () => import("./icons/npm-icon.tsx").then((mod) => mod.NPMIcon),
	PayPalIcon: () => import("./icons/paypal-icon.tsx").then((mod) => mod.PayPalIcon),
	PnpmIcon: () => import("./icons/pnpm-icon.tsx").then((mod) => mod.PnpmIcon),
	ReactIcon: () => import("./icons/react-icon.tsx").then((mod) => mod.ReactIcon),
	Spinner: () => import("./icons/spinner-icon.tsx").then((mod) => mod.Spinner),
	TailwindIcon: () => import("./icons/tailwind-icon.tsx").then((mod) => mod.TailwindIcon),
	TypeScriptIcon: () => import("./icons/typescript-icon.tsx").then((mod) => mod.TypeScriptIcon),
	YarnIcon: () => import("./icons/yarn-icon.tsx").then((mod) => mod.YarnIcon),
});
