import Head from "next/head";
import { GenIcon } from "react-icons";
import { BsFillMoonFill, BsFillSunFill } from "react-icons/bs";
import { AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube } from "react-icons/ai";
import Image from "next/image";
import devEdWave from "../public/dev-ed-wave.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import { useState, MouseEvent } from "react";

export default function Home() {
	const [theme, setTheme] = useState<boolean>(false);
	const handleTheme = (e: MouseEvent<HTMLLIElement>) => {
		setTheme(!theme);
	};
	return (
		<div className={(theme ? "dark" : "light") + " transition duration-150 ease-in-out"}>
			<Head>
				<title>Niels Plug Portfolio</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="bg-slate-200 px-10 md:px-20 lg:px-40 xl:px-60 dark:bg-slate-900">
				<section className="min-h-screen">
					<nav className="pt-5 pb-10 mb-12 flex justify-between">
						<h1 className="text-xl font-pacifico bg-gradient-to-r bg-clip-text text-transparent from-red-500 to-amber-500 dark:from-indigo-500 dark:to-blue-500">
							Niels Plug
						</h1>
						<ul className="flex items-center">
							<li
								onClick={handleTheme}
								className="bg-gradient-to-r from-red-500 to-amber-500 dark:from-indigo-500 dark:to-blue-500 p-2 rounded-full"
							>
								{theme ? (
									<>
										<BsFillMoonFill className="cursor-pointer text-2xl text-slate-900" />
									</>
								) : (
									<BsFillSunFill className="cursor-pointer text-2xl text-slate-50" />
								)}
							</li>
							<li>
								<a
									href="#"
									className="bg-gradient-to-r from-red-500 to-amber-500 dark:from-indigo-500 dark:to-blue-500 text-white font-semibold px-4 py-2 rounded-md ml-8"
								>
									Button
								</a>
							</li>
						</ul>
					</nav>
					<div className="text-center p-10">
						<h2 className="text-5xl font-pacifico pt-2 pb-4 text-teal-500 font-medium bg-gradient-to-r bg-clip-text text-transparent from-red-500 to-amber-500 dark:from-indigo-500 dark:to-blue-500 md:text-6xl">
							Niels Plug
						</h2>
						<h3 className="text-2xl font-opensans py2 dark:text-white">Junior Developer</h3>
						<p className="text-md font-roboto py-5 leading-8 text-gray-800 dark:text-gray-200">
							[paste small description here]
						</p>
					</div>
					<div className="text-5xl flex justify-center gap-16 text-gray-600">
						<AiFillTwitterCircle />
						<AiFillLinkedin />
						<AiFillYoutube />
					</div>
					<div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden">
						<Image src={devEdWave} layout="fill" objectFit="cover" />
					</div>
				</section>
				<section>
					<div>
						<h3 className="text-3xl py-1">Services I offer</h3>
						<p className="text-md py-2 leading-8 text-gray-800">
							Since the beginning of my journey as a freelance designer and developer, I&apos;ve done
							remote work for <span className="text-teal-500"> agencies </span>consulted for{" "}
							<span className="text-teal-500">startups </span>and collaborated with talanted people to
							create digital products for both business and consumer use
						</p>

						<p className="text-md py-2 leading-8 text-gray-800 ">
							I offer from a wide range of services, including brand design, programming and teaching.
						</p>
					</div>
					<div>
						<div className="text-center shadow-xl p-10 rounded-xl my-10">
							<Image src={design} width={100} height={100} />
							<h3 className="text-lg font-medium pt-8 pb-2">Beautiful Designs</h3>
							<p className="py-2">
								Creating elegant designs suited for your needs following core design theory.
							</p>
							<h4 className="text-teal-600 py-4">Design tools I use</h4>
							<p className="text-gray-800 py-1">Photoshop</p>
							<p className="text-gray-800 py-1">Illustrator</p>
							<p className="text-gray-800 py-1">Figma</p>
						</div>
						<div className="text-center shadow-xl p-10 rounded-xl my-10">
							<Image src={code} width={100} height={100} />
							<h3 className="text-lg font-medium pt-8 pb-2">Beautiful Designs</h3>
							<p className="py-2">
								Creating elegant designs suited for your needs following core design theory.
							</p>
							<h4 className="text-teal-600 py-4">Design tools I use</h4>
							<p className="text-gray-800 py-1">Photoshop</p>
							<p className="text-gray-800 py-1">Illustrator</p>
							<p className="text-gray-800 py-1">Figma</p>
						</div>
						<div className="text-center shadow-xl p-10 rounded-xl my-10">
							<Image src={consulting} width={100} height={100} />
							<h3 className="text-lg font-medium pt-8 pb-2">Beautiful Designs</h3>
							<p className="py-2">
								Creating elegant designs suited for your needs following core design theory.
							</p>
							<h4 className="text-teal-600 py-4">Design tools I use</h4>
							<p className="text-gray-800 py-1">Photoshop</p>
							<p className="text-gray-800 py-1">Illustrator</p>
							<p className="text-gray-800 py-1">Figma</p>
						</div>
					</div>
				</section>
				<section>
					<div>
						<h3 className="text-3xl py-1">Portfolio</h3>
					</div>
				</section>
			</main>
		</div>
	);
}
